language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls flake8
# command to run tests
script:
  - python3 setup.py install
  - flake8 --max-line-length=120 --exclude=venv,__pycache__
  - coverage run --source=VirtualJudgeSpider setup.py test
  - coverage report
after_success:
  coveralls